version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --save --legacy-peer-deps
  build:
    commands:
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
    #- "dist/e-commerce-frontend/**/*"
  base-directory: 'dist/e-commerce-frontend'
  #discard-paths: yes